### ISSUE TITLE
APScheduler  __init__.py failure ?

### ISSUE THREAD

**Issue by neandr** [agronholm/apscheduler#145]
After a new install of Jessie on a raspberry my program terminates with this error:
```
 Traceback (most recent call last):
  File "./piSchedule.py", line 33, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/__init__.py", line 3, in <module>
    version_info = tuple(int(x) if x.isdigit() else x for x in parsed_version.public.split('.'))
AttributeError: 'tuple' object has no attribute 'public
```
Up to line #33 the program only loads with 'import' / 'from' / etc..
Comparing `__init__.py` with a previous installation on Wheezy I found changing the file to the 'old' code my program works also on Jessie installation.

Here is the code:
```
pi@raspberrypi2:~ $ cat /usr/local/lib/python2.7/dist-packages/apscheduler/__init__.py
# These will be removed in APScheduler 4.0.

# --- this throws error ------------
#parsed_version = __import__('pkg_resources').get_distribution('APScheduler').parsed_version
#version_info = tuple(int(x) if x.isdigit() else x for x in parsed_version.public.split('.'))
#version = parsed_version.base_version
#release = __version__ = parsed_version.public
#del parsed_version
# --- end of 'wrong' code ------------


# --- this following 'old' code works  ----
version_info = (3, 0, 5)
version = '3.0.5'
release = '3.0.5'

__version__ = release  # PEP 396

pi@raspberrypi2: $ 
```

Any idea? Need more details? Which?

**Comment by agronholm** [comment]
This is about the 8th report of the same problem (#130), fixed by changeset 72769abb97751051fedc47b8c5f13cde3f44bec1.

**Comment by agronholm** [comment]
Before the next release, just upgrade your setuptools. That is what is causing this.

**Comment by neandr** [comment]
Sorry, already run an upgrade on that!
```
pi@raspberrypi2:~ $ sudo apt-get install python-setuptools
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
python-setuptools ist schon die neueste Version.
python-setuptools wurde als manuell installiert festgelegt.
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 14 nicht aktualisiert.
pi@raspberrypi2:~ $ 
```
And sorry to be the 8th, but I didn't expected to run into such a problem with a total fresh install with Jessie and APScheduler! I used the same install procedure as it was with Wheezy at the beginning of this year.

Is there another way to solve the problem as
-- updating  setuptools doesn't solve the problem
-- editing the  `__init__.py` isn't the way to offer to "end-user" of programs using APScheduler

More ideas?

**Comment by agronholm** [comment]
Upgrading setuptools through apt-get will probably still give you a very old version. You need to use pip to upgrade it: `pip install -U --user setuptools`.

**Comment by agronholm** [comment]
Alternatively you can install APScheduler 3.0.6 which does not have this problem.

**Comment by neandr** [comment]
Thanks, used your pip install recommendation and it works.
(Maybe  a note/warning for Raspberry users would be helpful?)

**Comment by agronholm** [comment]
This problem will go away in the next release which will happen soon.
